version: '3.8'

# Simple Login Application - MongoDB Only
# This is the simplified configuration for local development
# Students run backend and frontend locally, only MongoDB in Docker

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: mongodb-simple-login
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: simple_login
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local

# For full Docker deployment (backend + frontend + nginx), see:
# docs/for-developers/docker-compose.full.yml
